#!/bin/bash

if [ $# -eq 0 ]; then
  echo "Usage: $0 <script_to_execute>"
  exit 1
fi

SCRIPT_TO_EXECUTE=$1
COUNT_THRESHOLD=8
WAIT_COUNT=0

while true; do
  OUTPUT=$(npu-smi info)
  COUNT=$(echo "$OUTPUT" | grep -o 'No running processes found in NPU' | wc -l)

  if [ "$COUNT" -ge "$COUNT_THRESHOLD" ]; then
    bash $SCRIPT_TO_EXECUTE
    break
  else
    WAIT_COUNT=$((WAIT_COUNT + 1))
    echo "Waiting... $WAIT_COUNT"
    sleep 10
  fi
done
